---
services:
  web: 
    image: django_dconf:v1.2
    env_file:
      - .env
    volumes:
      - static_data:/app/files
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    env_file:
      - .env
  proxy:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_data:/app/files
      - type: bind
        source: ../deployment/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf

volumes:
  static_data:
